-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 11:57:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema totallynotairbnb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `totallynotairbnb` ;

-- -----------------------------------------------------
-- Schema totallynotairbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `totallynotairbnb` DEFAULT CHARACTER SET utf8 ;
USE `totallynotairbnb` ;

-- -----------------------------------------------------
-- Table `totallynotairbnb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(300) NOT NULL,
  `motDePasse` VARCHAR(25) NOT NULL,
  `telephone` VARCHAR(30) NOT NULL,
  `dateDeNaissance` DATE NOT NULL,
  `dateDeCreation` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `compteCertif` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`logement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(150) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  `prix` DECIMAL(5,2) NOT NULL,
  `description` TEXT(3000) NOT NULL,
  `dateDeModification` TIMESTAMP(6) NOT NULL,
  `dateDeCreation` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `nbDePieces` INT(2) NOT NULL,
  `nbDePlaces` INT(3) NOT NULL,
  `utilisateurId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logement_utilisateur1_idx` (`utilisateurId` ASC),
  CONSTRAINT `fk_logement_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `totallynotairbnb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`typeLogement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`typeLogement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `logementId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_typeLogement_logement1_idx` (`logementId` ASC),
  CONSTRAINT `fk_typeLogement_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `logementId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_logement1_idx` (`logementId` ASC),
  CONSTRAINT `fk_services_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`disponibilites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`disponibilites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateDispoDebut` DATE NOT NULL,
  `dateDispoFin` DATE NOT NULL,
  `estDisponible` TINYINT NOT NULL DEFAULT 0,
  `logementId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disponibilites_logement1_idx` (`logementId` ASC),
  CONSTRAINT `fk_disponibilites_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(2000) NOT NULL,
  `dateEnvoi` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `dateModif` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateurId` INT NOT NULL,
  `logementId` INT NOT NULL,
  `dateReservation` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_utilisateur1_idx` (`utilisateurId` ASC),
  INDEX `fk_reservation_logement1_idx` (`logementId` ASC),
  CONSTRAINT `fk_reservation_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `totallynotairbnb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`echanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`echanges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateurId` INT NOT NULL,
  `messageId` INT NOT NULL,
  `reservationId` INT NOT NULL,
  `dateDeCreation` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX `fk_utilisateur_has_message_message1_idx` (`messageId` ASC),
  INDEX `fk_utilisateur_has_message_utilisateur_idx` (`utilisateurId` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_messagerie_reservation1_idx` (`reservationId` ASC),
  CONSTRAINT `fk_utilisateur_has_message_utilisateur`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `totallynotairbnb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_message_message1`
    FOREIGN KEY (`messageId`)
    REFERENCES `totallynotairbnb`.`message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messagerie_reservation1`
    FOREIGN KEY (`reservationId`)
    REFERENCES `totallynotairbnb`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`avis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` INT(1) NOT NULL,
  `commentaire` TEXT(3000) NULL,
  `logementId` INT NOT NULL,
  `utilisateurId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avis_logement1_idx` (`logementId` ASC),
  INDEX `fk_avis_utilisateur1_idx` (`utilisateurId` ASC),
  CONSTRAINT `fk_avis_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avis_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `totallynotairbnb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NOT NULL,
  `logementId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_photos_logement1_idx` (`logementId` ASC),
  CONSTRAINT `fk_photos_logement1`
    FOREIGN KEY (`logementId`)
    REFERENCES `totallynotairbnb`.`logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `totallynotairbnb`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `totallynotairbnb`.`facture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateDeDelivrance` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `dateEcheance` DATE NOT NULL,
  `utilisateurId` INT NOT NULL,
  `reservationId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facture_utilisateur1_idx` (`utilisateurId` ASC),
  INDEX `fk_facture_reservation1_idx` (`reservationId` ASC),
  CONSTRAINT `fk_facture_utilisateur1`
    FOREIGN KEY (`utilisateurId`)
    REFERENCES `totallynotairbnb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_reservation1`
    FOREIGN KEY (`reservationId`)
    REFERENCES `totallynotairbnb`.`reservation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
